//
// Created by Delebrith on 24.11.2017.
//

#ifndef NEURAL_NETWORK_SENTENCEANALYSISNETWORK_H
#define NEURAL_NETWORK_SENTENCEANALYSISNETWORK_H


class SentenceAnalysisNetwork {

};


#endif //NEURAL_NETWORK_SENTENCEANALYSISNETWORK_H
